# Generated by Django 4.2.2 on 2024-12-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2Oapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
